{% set version = "8.3.1" %}

{% set base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: singlejar
  version: {{ version }}

source:
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: 79da863df05fa4de79a82c4f9d4e710766f040bc519fd8b184a4d4d51345d5ba
    patches:
      # Keep these patches in sync with the relevant ones from bazel-feedstock.
      - patches/0001-allow-args-to-be-passed-to-bazel_build.patch
      - patches/0002-Build-with-native-dependencies.patch
      - patches/0003-use-C-17.patch

  - fn: bazel
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64    # [build_platform == "linux-64"]
    sha256: 6b238b730c63081aed681dd2818072f73551881c0cc7976ebfb749a4aa8097fe    # [build_platform == "linux-64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-x86_64   # [build_platform == "osx-64"]
    sha256: 923e9d033fdea18effd3b1d0abb62dc85556347bfc1cfca9b2c69f00feaf6d6d    # [build_platform == "osx-64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64    # [build_platform == "osx-arm64"]
    sha256: 08a3a9919b60e7925597f5c136ef58ff56ca0864e1b15557dd3e659dc5739280    # [build_platform == "osx-arm64"]

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain >=0.2.0
    - openjdk
    - libprotobuf
    - sed
  host:
    - libabseil
    - libprotobuf
    - protobuf-bazel-rules

test:
  commands:
    - test -f $PREFIX/bin/singlejar
    - test -f $PREFIX/bin/singlejar_local

about:
  home: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: A tool for generating singleton jars

extra:
  recipe-maintainers:
    - xhochy
    - h-vetinari
    - conda-forge/bazel
